### ISSUE TITLE
The uploaded file exceeds the upload_max_filesize directive in php.ini.

### ISSUE THREAD

**Issue by michael-pov-it** [GoogleCloudPlatform/deploystack-wordpress-on-cloudrun#30]
Hello!
Could someone help me, how to increase upload_max_filesize in php.ini ?
Thx in advance.

**Comment by laurentgrangeau** [comment]
Hello,
I think the best thing to do is to build a custom image containing the modified php.ini file.
You can follow the instructions on the official Wordpress image page: https://hub.docker.com/_/wordpress
Then just modify the `var.wordpress_image` variable: https://github.com/GoogleCloudPlatform/deploystack-wordpress-on-cloudrun/blob/main/variables.tf#L89C11-L89C26 with the new image generated
